name: thyi_generator
description: A sample command-line application.
version: 1.0.0
homepage: http://github.com/huhuang03/thyi.flutter
author: th <huhuang03@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path:
  build:
  source_gen:
  thyi:
    path: ../thyi/
  code_builder:
  dart_style:
  json_serializable:
  analyzer:


dev_dependencies:
  pedantic:
  test: ^1.6.0
